# Generated by Django 5.0.7 on 2026-01-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_category_transaction_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('wallet', 'Digital Wallet'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
